// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.10.1
// source: FuseMessage.proto

package filewatcher_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyAccessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *NotifyAccessReq) Reset() {
	*x = NotifyAccessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyAccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyAccessReq) ProtoMessage() {}

func (x *NotifyAccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAccessReq.ProtoReflect.Descriptor instead.
func (*NotifyAccessReq) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyAccessReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NotifyAccessResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyAccessResp) Reset() {
	*x = NotifyAccessResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyAccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyAccessResp) ProtoMessage() {}

func (x *NotifyAccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAccessResp.ProtoReflect.Descriptor instead.
func (*NotifyAccessResp) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{1}
}

type NotifyReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *NotifyReadReq) Reset() {
	*x = NotifyReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReadReq) ProtoMessage() {}

func (x *NotifyReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReadReq.ProtoReflect.Descriptor instead.
func (*NotifyReadReq) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyReadReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NotifyReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyReadResp) Reset() {
	*x = NotifyReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReadResp) ProtoMessage() {}

func (x *NotifyReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReadResp.ProtoReflect.Descriptor instead.
func (*NotifyReadResp) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{3}
}

type ReadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadFileReq) Reset() {
	*x = ReadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileReq) ProtoMessage() {}

func (x *ReadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileReq.ProtoReflect.Descriptor instead.
func (*ReadFileReq) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data            []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorIsNotExist bool   `protobuf:"varint,3,opt,name=error_is_not_exist,json=errorIsNotExist,proto3" json:"error_is_not_exist,omitempty"`
	Mode            uint64 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReadFileResp) Reset() {
	*x = ReadFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResp) ProtoMessage() {}

func (x *ReadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResp.ProtoReflect.Descriptor instead.
func (*ReadFileResp) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadFileResp) GetErrorIsNotExist() bool {
	if x != nil {
		return x.ErrorIsNotExist
	}
	return false
}

func (x *ReadFileResp) GetMode() uint64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type Dirent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDir bool   `protobuf:"varint,1,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Dirent) Reset() {
	*x = Dirent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dirent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dirent) ProtoMessage() {}

func (x *Dirent) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dirent.ProtoReflect.Descriptor instead.
func (*Dirent) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{6}
}

func (x *Dirent) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *Dirent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadDirReq) Reset() {
	*x = ReadDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirReq) ProtoMessage() {}

func (x *ReadDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirReq.ProtoReflect.Descriptor instead.
func (*ReadDirReq) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{7}
}

func (x *ReadDirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries         []*Dirent `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error           string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorIsNotExist bool      `protobuf:"varint,3,opt,name=error_is_not_exist,json=errorIsNotExist,proto3" json:"error_is_not_exist,omitempty"`
	ErrorIsNotDir   bool      `protobuf:"varint,4,opt,name=error_is_not_dir,json=errorIsNotDir,proto3" json:"error_is_not_dir,omitempty"`
	Mode            uint64    `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReadDirResp) Reset() {
	*x = ReadDirResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResp) ProtoMessage() {}

func (x *ReadDirResp) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResp.ProtoReflect.Descriptor instead.
func (*ReadDirResp) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ReadDirResp) GetEntries() []*Dirent {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReadDirResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadDirResp) GetErrorIsNotExist() bool {
	if x != nil {
		return x.ErrorIsNotExist
	}
	return false
}

func (x *ReadDirResp) GetErrorIsNotDir() bool {
	if x != nil {
		return x.ErrorIsNotDir
	}
	return false
}

func (x *ReadDirResp) GetMode() uint64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type StatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *StatReq) Reset() {
	*x = StatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FuseMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReq) ProtoMessage() {}

func (x *StatReq) ProtoReflect() protoreflect.Message {
	mi := &file_FuseMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReq.ProtoReflect.Descriptor instead.
func (*StatReq) Descriptor() ([]byte, []int) {
	return file_FuseMessage_proto_rawDescGZIP(), []int{9}
}

func (x *StatReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_FuseMessage_proto protoreflect.FileDescriptor

var file_FuseMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x46, 0x75, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x25, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x12, 0x0a,
	0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x23, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x79, 0x0a, 0x0c, 0x52,
	0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x12, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x33, 0x0a, 0x06, 0x44, 0x69, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x52,
	0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xc2, 0x01,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x12, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x69, 0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x73, 0x4e, 0x6f, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x44, 0x69, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x32, 0xd5, 0x02, 0x0a, 0x06, 0x46, 0x75, 0x73, 0x65, 0x46, 0x53, 0x12, 0x59, 0x0a, 0x0c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x22, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x23, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x61, 0x64, 0x12, 0x20, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x08,
	0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4a, 0x0a,
	0x07, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x3b,
	0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FuseMessage_proto_rawDescOnce sync.Once
	file_FuseMessage_proto_rawDescData = file_FuseMessage_proto_rawDesc
)

func file_FuseMessage_proto_rawDescGZIP() []byte {
	file_FuseMessage_proto_rawDescOnce.Do(func() {
		file_FuseMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_FuseMessage_proto_rawDescData)
	})
	return file_FuseMessage_proto_rawDescData
}

var file_FuseMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_FuseMessage_proto_goTypes = []interface{}{
	(*NotifyAccessReq)(nil),  // 0: filewatcher_model.NotifyAccessReq
	(*NotifyAccessResp)(nil), // 1: filewatcher_model.NotifyAccessResp
	(*NotifyReadReq)(nil),    // 2: filewatcher_model.NotifyReadReq
	(*NotifyReadResp)(nil),   // 3: filewatcher_model.NotifyReadResp
	(*ReadFileReq)(nil),      // 4: filewatcher_model.ReadFileReq
	(*ReadFileResp)(nil),     // 5: filewatcher_model.ReadFileResp
	(*Dirent)(nil),           // 6: filewatcher_model.Dirent
	(*ReadDirReq)(nil),       // 7: filewatcher_model.ReadDirReq
	(*ReadDirResp)(nil),      // 8: filewatcher_model.ReadDirResp
	(*StatReq)(nil),          // 9: filewatcher_model.StatReq
}
var file_FuseMessage_proto_depIdxs = []int32{
	6, // 0: filewatcher_model.ReadDirResp.entries:type_name -> filewatcher_model.Dirent
	0, // 1: filewatcher_model.FuseFS.NotifyAccess:input_type -> filewatcher_model.NotifyAccessReq
	2, // 2: filewatcher_model.FuseFS.NotifyRead:input_type -> filewatcher_model.NotifyReadReq
	4, // 3: filewatcher_model.FuseFS.ReadFile:input_type -> filewatcher_model.ReadFileReq
	7, // 4: filewatcher_model.FuseFS.ReadDir:input_type -> filewatcher_model.ReadDirReq
	1, // 5: filewatcher_model.FuseFS.NotifyAccess:output_type -> filewatcher_model.NotifyAccessResp
	3, // 6: filewatcher_model.FuseFS.NotifyRead:output_type -> filewatcher_model.NotifyReadResp
	5, // 7: filewatcher_model.FuseFS.ReadFile:output_type -> filewatcher_model.ReadFileResp
	8, // 8: filewatcher_model.FuseFS.ReadDir:output_type -> filewatcher_model.ReadDirResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_FuseMessage_proto_init() }
func file_FuseMessage_proto_init() {
	if File_FuseMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FuseMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyAccessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyAccessResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dirent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FuseMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FuseMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_FuseMessage_proto_goTypes,
		DependencyIndexes: file_FuseMessage_proto_depIdxs,
		MessageInfos:      file_FuseMessage_proto_msgTypes,
	}.Build()
	File_FuseMessage_proto = out.File
	file_FuseMessage_proto_rawDesc = nil
	file_FuseMessage_proto_goTypes = nil
	file_FuseMessage_proto_depIdxs = nil
}
