// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.10.1
// source: MetaMessage.proto

package filewatcher_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *ReconnectReq) Reset() {
	*x = ReconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReq) ProtoMessage() {}

func (x *ReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReq.ProtoReflect.Descriptor instead.
func (*ReconnectReq) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ReconnectReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type ReconnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *ReconnectResp) Reset() {
	*x = ReconnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectResp) ProtoMessage() {}

func (x *ReconnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectResp.ProtoReflect.Descriptor instead.
func (*ReconnectResp) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ReconnectResp) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type AllowReadsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllowReadsReq) Reset() {
	*x = AllowReadsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowReadsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowReadsReq) ProtoMessage() {}

func (x *AllowReadsReq) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowReadsReq.ProtoReflect.Descriptor instead.
func (*AllowReadsReq) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{2}
}

type AllowReadsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllowReadsResp) Reset() {
	*x = AllowReadsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowReadsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowReadsResp) ProtoMessage() {}

func (x *AllowReadsResp) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowReadsResp.ProtoReflect.Descriptor instead.
func (*AllowReadsResp) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{3}
}

type SyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncReq) Reset() {
	*x = SyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq) ProtoMessage() {}

func (x *SyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq.ProtoReflect.Descriptor instead.
func (*SyncReq) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{4}
}

type SyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncResp) Reset() {
	*x = SyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResp) ProtoMessage() {}

func (x *SyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResp.ProtoReflect.Descriptor instead.
func (*SyncResp) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{5}
}

type CopyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostSource string `protobuf:"bytes,1,opt,name=host_source,json=hostSource,proto3" json:"host_source,omitempty"`
}

func (x *CopyReq) Reset() {
	*x = CopyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyReq) ProtoMessage() {}

func (x *CopyReq) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyReq.ProtoReflect.Descriptor instead.
func (*CopyReq) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{6}
}

func (x *CopyReq) GetHostSource() string {
	if x != nil {
		return x.HostSource
	}
	return ""
}

type CopyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CopyResp) Reset() {
	*x = CopyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MetaMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResp) ProtoMessage() {}

func (x *CopyResp) ProtoReflect() protoreflect.Message {
	mi := &file_MetaMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResp.ProtoReflect.Descriptor instead.
func (*CopyResp) Descriptor() ([]byte, []int) {
	return file_MetaMessage_proto_rawDescGZIP(), []int{7}
}

func (x *CopyResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_MetaMessage_proto protoreflect.FileDescriptor

var file_MetaMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x65, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22,
	0x0f, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x22, 0x10, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x22, 0x0a, 0x0a,
	0x08, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x07, 0x43, 0x6f, 0x70,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x6f, 0x73, 0x74, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xc4, 0x02, 0x0a, 0x15, 0x46, 0x75, 0x73, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x50, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64,
	0x73, 0x12, 0x20, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63,
	0x12, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x43,
	0x6f, 0x70, 0x79, 0x12, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16,
	0x5a, 0x14, 0x2e, 0x2f, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MetaMessage_proto_rawDescOnce sync.Once
	file_MetaMessage_proto_rawDescData = file_MetaMessage_proto_rawDesc
)

func file_MetaMessage_proto_rawDescGZIP() []byte {
	file_MetaMessage_proto_rawDescOnce.Do(func() {
		file_MetaMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_MetaMessage_proto_rawDescData)
	})
	return file_MetaMessage_proto_rawDescData
}

var file_MetaMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_MetaMessage_proto_goTypes = []interface{}{
	(*ReconnectReq)(nil),   // 0: filewatcher_model.ReconnectReq
	(*ReconnectResp)(nil),  // 1: filewatcher_model.ReconnectResp
	(*AllowReadsReq)(nil),  // 2: filewatcher_model.AllowReadsReq
	(*AllowReadsResp)(nil), // 3: filewatcher_model.AllowReadsResp
	(*SyncReq)(nil),        // 4: filewatcher_model.SyncReq
	(*SyncResp)(nil),       // 5: filewatcher_model.SyncResp
	(*CopyReq)(nil),        // 6: filewatcher_model.CopyReq
	(*CopyResp)(nil),       // 7: filewatcher_model.CopyResp
}
var file_MetaMessage_proto_depIdxs = []int32{
	0, // 0: filewatcher_model.FuseFilewatcherClient.Reconnect:input_type -> filewatcher_model.ReconnectReq
	2, // 1: filewatcher_model.FuseFilewatcherClient.AllowReads:input_type -> filewatcher_model.AllowReadsReq
	4, // 2: filewatcher_model.FuseFilewatcherClient.Sync:input_type -> filewatcher_model.SyncReq
	6, // 3: filewatcher_model.FuseFilewatcherClient.Copy:input_type -> filewatcher_model.CopyReq
	1, // 4: filewatcher_model.FuseFilewatcherClient.Reconnect:output_type -> filewatcher_model.ReconnectResp
	3, // 5: filewatcher_model.FuseFilewatcherClient.AllowReads:output_type -> filewatcher_model.AllowReadsResp
	5, // 6: filewatcher_model.FuseFilewatcherClient.Sync:output_type -> filewatcher_model.SyncResp
	7, // 7: filewatcher_model.FuseFilewatcherClient.Copy:output_type -> filewatcher_model.CopyResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MetaMessage_proto_init() }
func file_MetaMessage_proto_init() {
	if File_MetaMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MetaMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowReadsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowReadsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MetaMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MetaMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MetaMessage_proto_goTypes,
		DependencyIndexes: file_MetaMessage_proto_depIdxs,
		MessageInfos:      file_MetaMessage_proto_msgTypes,
	}.Build()
	File_MetaMessage_proto = out.File
	file_MetaMessage_proto_rawDesc = nil
	file_MetaMessage_proto_goTypes = nil
	file_MetaMessage_proto_depIdxs = nil
}
