// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.10.1
// source: ClientMessage.proto

package vm_protocol_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *ReconnectReq) Reset() {
	*x = ReconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReq) ProtoMessage() {}

func (x *ReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReq.ProtoReflect.Descriptor instead.
func (*ReconnectReq) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ReconnectReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type ReconnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *ReconnectResp) Reset() {
	*x = ReconnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectResp) ProtoMessage() {}

func (x *ReconnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectResp.ProtoReflect.Descriptor instead.
func (*ReconnectResp) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ReconnectResp) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type AllowReadsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllowReadsReq) Reset() {
	*x = AllowReadsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowReadsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowReadsReq) ProtoMessage() {}

func (x *AllowReadsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowReadsReq.ProtoReflect.Descriptor instead.
func (*AllowReadsReq) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{2}
}

type AllowReadsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllowReadsResp) Reset() {
	*x = AllowReadsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowReadsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowReadsResp) ProtoMessage() {}

func (x *AllowReadsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowReadsResp.ProtoReflect.Descriptor instead.
func (*AllowReadsResp) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{3}
}

type SyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncReq) Reset() {
	*x = SyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq) ProtoMessage() {}

func (x *SyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq.ProtoReflect.Descriptor instead.
func (*SyncReq) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{4}
}

type SyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncResp) Reset() {
	*x = SyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResp) ProtoMessage() {}

func (x *SyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResp.ProtoReflect.Descriptor instead.
func (*SyncResp) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{5}
}

type CopyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostSource string `protobuf:"bytes,1,opt,name=host_source,json=hostSource,proto3" json:"host_source,omitempty"`
}

func (x *CopyReq) Reset() {
	*x = CopyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyReq) ProtoMessage() {}

func (x *CopyReq) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyReq.ProtoReflect.Descriptor instead.
func (*CopyReq) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{6}
}

func (x *CopyReq) GetHostSource() string {
	if x != nil {
		return x.HostSource
	}
	return ""
}

type CopyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CopyResp) Reset() {
	*x = CopyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResp) ProtoMessage() {}

func (x *CopyResp) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResp.ProtoReflect.Descriptor instead.
func (*CopyResp) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{7}
}

func (x *CopyResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExposeWebsiteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExposeWebsiteLine string `protobuf:"bytes,1,opt,name=expose_website_line,json=exposeWebsiteLine,proto3" json:"expose_website_line,omitempty"`
}

func (x *ExposeWebsiteReq) Reset() {
	*x = ExposeWebsiteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExposeWebsiteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeWebsiteReq) ProtoMessage() {}

func (x *ExposeWebsiteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeWebsiteReq.ProtoReflect.Descriptor instead.
func (*ExposeWebsiteReq) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ExposeWebsiteReq) GetExposeWebsiteLine() string {
	if x != nil {
		return x.ExposeWebsiteLine
	}
	return ""
}

type ExposeWebsiteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ExposeWebsiteResp) Reset() {
	*x = ExposeWebsiteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExposeWebsiteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeWebsiteResp) ProtoMessage() {}

func (x *ExposeWebsiteResp) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeWebsiteResp.ProtoReflect.Descriptor instead.
func (*ExposeWebsiteResp) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{9}
}

func (x *ExposeWebsiteResp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_ClientMessage_proto protoreflect.FileDescriptor

var file_ClientMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x76, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x23, 0x0a, 0x0d,
	0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x22,
	0x0a, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x07, 0x43,
	0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x6f, 0x73,
	0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x10, 0x45, 0x78, 0x70,
	0x6f, 0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a,
	0x13, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x5f,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x65, 0x78, 0x70, 0x6f,
	0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x27, 0x0a,
	0x11, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x32, 0x9d, 0x03, 0x0a, 0x10, 0x56, 0x4d, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x50, 0x0a, 0x09, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x76, 0x6d, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x76, 0x6d, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x53, 0x0a,
	0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x76, 0x6d,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e,
	0x76, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1a, 0x2e, 0x76, 0x6d, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x76, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x1a, 0x2e,
	0x76, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x76, 0x6d, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f,
	0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f,
	0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x76, 0x6d, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x78,
	0x70, 0x6f, 0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24,
	0x2e, 0x76, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x3b, 0x76, 0x6d, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ClientMessage_proto_rawDescOnce sync.Once
	file_ClientMessage_proto_rawDescData = file_ClientMessage_proto_rawDesc
)

func file_ClientMessage_proto_rawDescGZIP() []byte {
	file_ClientMessage_proto_rawDescOnce.Do(func() {
		file_ClientMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientMessage_proto_rawDescData)
	})
	return file_ClientMessage_proto_rawDescData
}

var file_ClientMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ClientMessage_proto_goTypes = []interface{}{
	(*ReconnectReq)(nil),      // 0: vm_protocol_model.ReconnectReq
	(*ReconnectResp)(nil),     // 1: vm_protocol_model.ReconnectResp
	(*AllowReadsReq)(nil),     // 2: vm_protocol_model.AllowReadsReq
	(*AllowReadsResp)(nil),    // 3: vm_protocol_model.AllowReadsResp
	(*SyncReq)(nil),           // 4: vm_protocol_model.SyncReq
	(*SyncResp)(nil),          // 5: vm_protocol_model.SyncResp
	(*CopyReq)(nil),           // 6: vm_protocol_model.CopyReq
	(*CopyResp)(nil),          // 7: vm_protocol_model.CopyResp
	(*ExposeWebsiteReq)(nil),  // 8: vm_protocol_model.ExposeWebsiteReq
	(*ExposeWebsiteResp)(nil), // 9: vm_protocol_model.ExposeWebsiteResp
}
var file_ClientMessage_proto_depIdxs = []int32{
	0, // 0: vm_protocol_model.VMProtocolClient.Reconnect:input_type -> vm_protocol_model.ReconnectReq
	2, // 1: vm_protocol_model.VMProtocolClient.AllowReads:input_type -> vm_protocol_model.AllowReadsReq
	4, // 2: vm_protocol_model.VMProtocolClient.Sync:input_type -> vm_protocol_model.SyncReq
	6, // 3: vm_protocol_model.VMProtocolClient.Copy:input_type -> vm_protocol_model.CopyReq
	8, // 4: vm_protocol_model.VMProtocolClient.ExposeWebsite:input_type -> vm_protocol_model.ExposeWebsiteReq
	1, // 5: vm_protocol_model.VMProtocolClient.Reconnect:output_type -> vm_protocol_model.ReconnectResp
	3, // 6: vm_protocol_model.VMProtocolClient.AllowReads:output_type -> vm_protocol_model.AllowReadsResp
	5, // 7: vm_protocol_model.VMProtocolClient.Sync:output_type -> vm_protocol_model.SyncResp
	7, // 8: vm_protocol_model.VMProtocolClient.Copy:output_type -> vm_protocol_model.CopyResp
	9, // 9: vm_protocol_model.VMProtocolClient.ExposeWebsite:output_type -> vm_protocol_model.ExposeWebsiteResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ClientMessage_proto_init() }
func file_ClientMessage_proto_init() {
	if File_ClientMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ClientMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowReadsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowReadsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExposeWebsiteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExposeWebsiteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ClientMessage_proto_goTypes,
		DependencyIndexes: file_ClientMessage_proto_depIdxs,
		MessageInfos:      file_ClientMessage_proto_msgTypes,
	}.Build()
	File_ClientMessage_proto = out.File
	file_ClientMessage_proto_rawDesc = nil
	file_ClientMessage_proto_goTypes = nil
	file_ClientMessage_proto_depIdxs = nil
}
