// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vm_protocol_model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VMProtocolClientClient is the client API for VMProtocolClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMProtocolClientClient interface {
	Reconnect(ctx context.Context, in *ReconnectReq, opts ...grpc.CallOption) (*ReconnectResp, error)
	AllowReads(ctx context.Context, in *AllowReadsReq, opts ...grpc.CallOption) (*AllowReadsResp, error)
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error)
	Copy(ctx context.Context, in *CopyReq, opts ...grpc.CallOption) (*CopyResp, error)
	ExposeWebsite(ctx context.Context, in *ExposeWebsiteReq, opts ...grpc.CallOption) (*ExposeWebsiteResp, error)
}

type vMProtocolClientClient struct {
	cc grpc.ClientConnInterface
}

func NewVMProtocolClientClient(cc grpc.ClientConnInterface) VMProtocolClientClient {
	return &vMProtocolClientClient{cc}
}

func (c *vMProtocolClientClient) Reconnect(ctx context.Context, in *ReconnectReq, opts ...grpc.CallOption) (*ReconnectResp, error) {
	out := new(ReconnectResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolClient/Reconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolClientClient) AllowReads(ctx context.Context, in *AllowReadsReq, opts ...grpc.CallOption) (*AllowReadsResp, error) {
	out := new(AllowReadsResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolClient/AllowReads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolClientClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error) {
	out := new(SyncResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolClient/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolClientClient) Copy(ctx context.Context, in *CopyReq, opts ...grpc.CallOption) (*CopyResp, error) {
	out := new(CopyResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolClient/Copy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolClientClient) ExposeWebsite(ctx context.Context, in *ExposeWebsiteReq, opts ...grpc.CallOption) (*ExposeWebsiteResp, error) {
	out := new(ExposeWebsiteResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolClient/ExposeWebsite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMProtocolClientServer is the server API for VMProtocolClient service.
// All implementations must embed UnimplementedVMProtocolClientServer
// for forward compatibility
type VMProtocolClientServer interface {
	Reconnect(context.Context, *ReconnectReq) (*ReconnectResp, error)
	AllowReads(context.Context, *AllowReadsReq) (*AllowReadsResp, error)
	Sync(context.Context, *SyncReq) (*SyncResp, error)
	Copy(context.Context, *CopyReq) (*CopyResp, error)
	ExposeWebsite(context.Context, *ExposeWebsiteReq) (*ExposeWebsiteResp, error)
	mustEmbedUnimplementedVMProtocolClientServer()
}

// UnimplementedVMProtocolClientServer must be embedded to have forward compatible implementations.
type UnimplementedVMProtocolClientServer struct {
}

func (UnimplementedVMProtocolClientServer) Reconnect(context.Context, *ReconnectReq) (*ReconnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconnect not implemented")
}
func (UnimplementedVMProtocolClientServer) AllowReads(context.Context, *AllowReadsReq) (*AllowReadsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowReads not implemented")
}
func (UnimplementedVMProtocolClientServer) Sync(context.Context, *SyncReq) (*SyncResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedVMProtocolClientServer) Copy(context.Context, *CopyReq) (*CopyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedVMProtocolClientServer) ExposeWebsite(context.Context, *ExposeWebsiteReq) (*ExposeWebsiteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExposeWebsite not implemented")
}
func (UnimplementedVMProtocolClientServer) mustEmbedUnimplementedVMProtocolClientServer() {}

// UnsafeVMProtocolClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMProtocolClientServer will
// result in compilation errors.
type UnsafeVMProtocolClientServer interface {
	mustEmbedUnimplementedVMProtocolClientServer()
}

func RegisterVMProtocolClientServer(s grpc.ServiceRegistrar, srv VMProtocolClientServer) {
	s.RegisterService(&VMProtocolClient_ServiceDesc, srv)
}

func _VMProtocolClient_Reconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolClientServer).Reconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolClient/Reconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolClientServer).Reconnect(ctx, req.(*ReconnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolClient_AllowReads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowReadsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolClientServer).AllowReads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolClient/AllowReads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolClientServer).AllowReads(ctx, req.(*AllowReadsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolClient_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolClientServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolClient/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolClientServer).Sync(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolClient_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolClientServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolClient/Copy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolClientServer).Copy(ctx, req.(*CopyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolClient_ExposeWebsite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeWebsiteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolClientServer).ExposeWebsite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolClient/ExposeWebsite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolClientServer).ExposeWebsite(ctx, req.(*ExposeWebsiteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VMProtocolClient_ServiceDesc is the grpc.ServiceDesc for VMProtocolClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMProtocolClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vm_protocol_model.VMProtocolClient",
	HandlerType: (*VMProtocolClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reconnect",
			Handler:    _VMProtocolClient_Reconnect_Handler,
		},
		{
			MethodName: "AllowReads",
			Handler:    _VMProtocolClient_AllowReads_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _VMProtocolClient_Sync_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _VMProtocolClient_Copy_Handler,
		},
		{
			MethodName: "ExposeWebsite",
			Handler:    _VMProtocolClient_ExposeWebsite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ClientMessage.proto",
}
