// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vm_protocol_model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VMProtocolServerClient is the client API for VMProtocolServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMProtocolServerClient interface {
	NotifyAccess(ctx context.Context, in *NotifyAccessReq, opts ...grpc.CallOption) (*NotifyAccessResp, error)
	NotifyRead(ctx context.Context, in *NotifyReadReq, opts ...grpc.CallOption) (*NotifyReadResp, error)
	ReadFile(ctx context.Context, in *ReadFileReq, opts ...grpc.CallOption) (VMProtocolServer_ReadFileClient, error)
	ReadDir(ctx context.Context, in *ReadDirReq, opts ...grpc.CallOption) (*ReadDirResp, error)
}

type vMProtocolServerClient struct {
	cc grpc.ClientConnInterface
}

func NewVMProtocolServerClient(cc grpc.ClientConnInterface) VMProtocolServerClient {
	return &vMProtocolServerClient{cc}
}

func (c *vMProtocolServerClient) NotifyAccess(ctx context.Context, in *NotifyAccessReq, opts ...grpc.CallOption) (*NotifyAccessResp, error) {
	out := new(NotifyAccessResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolServer/NotifyAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolServerClient) NotifyRead(ctx context.Context, in *NotifyReadReq, opts ...grpc.CallOption) (*NotifyReadResp, error) {
	out := new(NotifyReadResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolServer/NotifyRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMProtocolServerClient) ReadFile(ctx context.Context, in *ReadFileReq, opts ...grpc.CallOption) (VMProtocolServer_ReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &VMProtocolServer_ServiceDesc.Streams[0], "/vm_protocol_model.VMProtocolServer/ReadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &vMProtocolServerReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VMProtocolServer_ReadFileClient interface {
	Recv() (*ReadFileResp, error)
	grpc.ClientStream
}

type vMProtocolServerReadFileClient struct {
	grpc.ClientStream
}

func (x *vMProtocolServerReadFileClient) Recv() (*ReadFileResp, error) {
	m := new(ReadFileResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vMProtocolServerClient) ReadDir(ctx context.Context, in *ReadDirReq, opts ...grpc.CallOption) (*ReadDirResp, error) {
	out := new(ReadDirResp)
	err := c.cc.Invoke(ctx, "/vm_protocol_model.VMProtocolServer/ReadDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMProtocolServerServer is the server API for VMProtocolServer service.
// All implementations must embed UnimplementedVMProtocolServerServer
// for forward compatibility
type VMProtocolServerServer interface {
	NotifyAccess(context.Context, *NotifyAccessReq) (*NotifyAccessResp, error)
	NotifyRead(context.Context, *NotifyReadReq) (*NotifyReadResp, error)
	ReadFile(*ReadFileReq, VMProtocolServer_ReadFileServer) error
	ReadDir(context.Context, *ReadDirReq) (*ReadDirResp, error)
	mustEmbedUnimplementedVMProtocolServerServer()
}

// UnimplementedVMProtocolServerServer must be embedded to have forward compatible implementations.
type UnimplementedVMProtocolServerServer struct {
}

func (UnimplementedVMProtocolServerServer) NotifyAccess(context.Context, *NotifyAccessReq) (*NotifyAccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAccess not implemented")
}
func (UnimplementedVMProtocolServerServer) NotifyRead(context.Context, *NotifyReadReq) (*NotifyReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyRead not implemented")
}
func (UnimplementedVMProtocolServerServer) ReadFile(*ReadFileReq, VMProtocolServer_ReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedVMProtocolServerServer) ReadDir(context.Context, *ReadDirReq) (*ReadDirResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDir not implemented")
}
func (UnimplementedVMProtocolServerServer) mustEmbedUnimplementedVMProtocolServerServer() {}

// UnsafeVMProtocolServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMProtocolServerServer will
// result in compilation errors.
type UnsafeVMProtocolServerServer interface {
	mustEmbedUnimplementedVMProtocolServerServer()
}

func RegisterVMProtocolServerServer(s grpc.ServiceRegistrar, srv VMProtocolServerServer) {
	s.RegisterService(&VMProtocolServer_ServiceDesc, srv)
}

func _VMProtocolServer_NotifyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolServerServer).NotifyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolServer/NotifyAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolServerServer).NotifyAccess(ctx, req.(*NotifyAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolServer_NotifyRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolServerServer).NotifyRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolServer/NotifyRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolServerServer).NotifyRead(ctx, req.(*NotifyReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMProtocolServer_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMProtocolServerServer).ReadFile(m, &vMProtocolServerReadFileServer{stream})
}

type VMProtocolServer_ReadFileServer interface {
	Send(*ReadFileResp) error
	grpc.ServerStream
}

type vMProtocolServerReadFileServer struct {
	grpc.ServerStream
}

func (x *vMProtocolServerReadFileServer) Send(m *ReadFileResp) error {
	return x.ServerStream.SendMsg(m)
}

func _VMProtocolServer_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMProtocolServerServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_protocol_model.VMProtocolServer/ReadDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMProtocolServerServer).ReadDir(ctx, req.(*ReadDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VMProtocolServer_ServiceDesc is the grpc.ServiceDesc for VMProtocolServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMProtocolServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vm_protocol_model.VMProtocolServer",
	HandlerType: (*VMProtocolServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAccess",
			Handler:    _VMProtocolServer_NotifyAccess_Handler,
		},
		{
			MethodName: "NotifyRead",
			Handler:    _VMProtocolServer_NotifyRead_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _VMProtocolServer_ReadDir_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _VMProtocolServer_ReadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ServerMessage.proto",
}
